# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    
    pool:
      vmImage: $(vmImageName)
    
    steps:  
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/Server0402.csproj'

- stage: Release
  displayName: Release stage

  jobs:
  - job: Release
    displayName: Release to Azure Web App

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Publish the WebApp
      inputs:
        command: 'publish'
        publishWebProjects: true
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Microsoft Azure 스폰서쉽(28697aaf-daed-4d77-b02a-c12345678900)'
        appType: 'webAppLinux'
        WebAppName: 'mingyu0402'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        RuntimeStack: 'DOTNETCORE|5.0'
